/*
 * Autogenerated file, DO NOT EDIT manually!
 *
 * Copyright (c) 2015 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

#include <linux/sysfs.h>

#include "i915_drv.h"

enum metric_set_id {
        METRIC_SET_ID_RENDER_BASIC = 1,
};

int i915_oa_n_builtin_metric_sets_hsw = 1;

static const struct i915_oa_reg b_counter_config_render_basic[] = {
	{ 0x2724, 0x00800000 },
	{ 0x2720, 0x00000000 },
	{ 0x2714, 0x00800000 },
	{ 0x2710, 0x00000000 },
};

static const struct i915_oa_reg mux_config_render_basic[] = {
	{ 0x253A4, 0x01600000 },
	{ 0x25440, 0x00100000 },
	{ 0x25128, 0x00000000 },
	{ 0x2691C, 0x00000800 },
	{ 0x26AA0, 0x01500000 },
	{ 0x26B9C, 0x00006000 },
	{ 0x2791C, 0x00000800 },
	{ 0x27AA0, 0x01500000 },
	{ 0x27B9C, 0x00006000 },
	{ 0x2641C, 0x00000400 },
	{ 0x25380, 0x00000010 },
	{ 0x2538C, 0x00000000 },
	{ 0x25384, 0x0800AAAA },
	{ 0x25400, 0x00000004 },
	{ 0x2540C, 0x06029000 },
	{ 0x25410, 0x00000002 },
	{ 0x25404, 0x5C30FFFF },
	{ 0x25100, 0x00000016 },
	{ 0x25110, 0x00000400 },
	{ 0x25104, 0x00000000 },
	{ 0x26804, 0x00001211 },
	{ 0x26884, 0x00000100 },
	{ 0x26900, 0x00000002 },
	{ 0x26908, 0x00700000 },
	{ 0x26904, 0x00000000 },
	{ 0x26984, 0x00001022 },
	{ 0x26A04, 0x00000011 },
	{ 0x26A80, 0x00000006 },
	{ 0x26A88, 0x00000C02 },
	{ 0x26A84, 0x00000000 },
	{ 0x26B04, 0x00001000 },
	{ 0x26B80, 0x00000002 },
	{ 0x26B8C, 0x00000007 },
	{ 0x26B84, 0x00000000 },
	{ 0x27804, 0x00004844 },
	{ 0x27884, 0x00000400 },
	{ 0x27900, 0x00000002 },
	{ 0x27908, 0x0E000000 },
	{ 0x27904, 0x00000000 },
	{ 0x27984, 0x00004088 },
	{ 0x27A04, 0x00000044 },
	{ 0x27A80, 0x00000006 },
	{ 0x27A88, 0x00018040 },
	{ 0x27A84, 0x00000000 },
	{ 0x27B04, 0x00004000 },
	{ 0x27B80, 0x00000002 },
	{ 0x27B8C, 0x000000E0 },
	{ 0x27B84, 0x00000000 },
	{ 0x26104, 0x00002222 },
	{ 0x26184, 0x0C006666 },
	{ 0x26284, 0x04000000 },
	{ 0x26304, 0x04000000 },
	{ 0x26400, 0x00000002 },
	{ 0x26410, 0x000000A0 },
	{ 0x26404, 0x00000000 },
	{ 0x25420, 0x04108020 },
	{ 0x25424, 0x1284A420 },
	{ 0x2541C, 0x00000000 },
	{ 0x25428, 0x00042049 },
};

static int select_render_basic_config(struct drm_i915_private *dev_priv)
{
        dev_priv->perf.oa.mux_regs =
                mux_config_render_basic;
        dev_priv->perf.oa.mux_regs_len =
                ARRAY_SIZE(mux_config_render_basic);

        dev_priv->perf.oa.b_counter_regs =
                b_counter_config_render_basic;
        dev_priv->perf.oa.b_counter_regs_len =
                ARRAY_SIZE(b_counter_config_render_basic);

        return 0;
}

int i915_oa_select_metric_set_hsw(struct drm_i915_private *dev_priv)
{
        dev_priv->perf.oa.mux_regs = NULL;
        dev_priv->perf.oa.mux_regs_len = 0;
        dev_priv->perf.oa.b_counter_regs = NULL;
        dev_priv->perf.oa.b_counter_regs_len = 0;

        switch (dev_priv->perf.oa.metrics_set) {
        case METRIC_SET_ID_RENDER_BASIC:
                return select_render_basic_config(dev_priv);
        default:
                return -ENODEV;
        }
}

static ssize_t
show_render_basic_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
        return sprintf(buf, "%d\n", METRIC_SET_ID_RENDER_BASIC);
}

static struct device_attribute dev_attr_render_basic_id = {
        .attr = { .name = "id", .mode = S_IRUGO },
        .show = show_render_basic_id,
        .store = NULL,
};

static struct attribute *attrs_render_basic[] = {
        &dev_attr_render_basic_id.attr,
        NULL,
};

static struct attribute_group group_render_basic = {
        .name = "403d8832-1a27-4aa6-a64e-f5389ce7b212",
        .attrs =  attrs_render_basic,
};

int
i915_perf_init_sysfs_hsw(struct drm_i915_private *dev_priv)
{
        int ret;

        ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_render_basic);
        if (ret)
                goto error_render_basic;

        return 0;

error_render_basic:
        return ret;
}

void
i915_perf_deinit_sysfs_hsw(struct drm_i915_private *dev_priv)
{
        sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_render_basic);
}
