/*
 * Autogenerated file, DO NOT EDIT manually!
 *
 * Copyright (c) 2015 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

#include <linux/sysfs.h>

#include "i915_drv.h"

enum metric_set_id {
	METRIC_SET_ID_RENDER_BASIC = 1,
};

int i915_oa_n_builtin_metric_sets_chv = 1;

static const struct i915_oa_reg b_counter_config_render_basic[] = {
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x00800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x00800000 },
};

static const struct i915_oa_reg flex_eu_config_render_basic[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_render_basic[] = {
	{ _MMIO(0x9888), 0x59800000 },
	{ _MMIO(0x9888), 0x59800001 },
	{ _MMIO(0x9888), 0x2C110014 },
	{ _MMIO(0x9888), 0x2E110000 },
	{ _MMIO(0x9888), 0x2C310014 },
	{ _MMIO(0x9888), 0x2E310000 },
	{ _MMIO(0x9888), 0x2B8303DF },
	{ _MMIO(0x9888), 0x358002C0 },
	{ _MMIO(0x9888), 0x00580888 },
	{ _MMIO(0x9888), 0x00190555 },
	{ _MMIO(0x9888), 0x00380444 },
	{ _MMIO(0x9888), 0x003A0666 },
	{ _MMIO(0x9888), 0x00100111 },
	{ _MMIO(0x9888), 0x06110030 },
	{ _MMIO(0x9888), 0x0A110031 },
	{ _MMIO(0x9888), 0x0E110046 },
	{ _MMIO(0x9888), 0x04110000 },
	{ _MMIO(0x9888), 0x00110000 },
	{ _MMIO(0x9888), 0x00130111 },
	{ _MMIO(0x9888), 0x00300444 },
	{ _MMIO(0x9888), 0x08310030 },
	{ _MMIO(0x9888), 0x0C310031 },
	{ _MMIO(0x9888), 0x10310046 },
	{ _MMIO(0x9888), 0x04310000 },
	{ _MMIO(0x9888), 0x00310000 },
	{ _MMIO(0x9888), 0x00330444 },
	{ _MMIO(0x9888), 0x018B0FFF },
	{ _MMIO(0x9888), 0x01855000 },
	{ _MMIO(0x9888), 0x03850555 },
	{ _MMIO(0x9888), 0x13830021 },
	{ _MMIO(0x9888), 0x15830020 },
	{ _MMIO(0x9888), 0x1783002F },
	{ _MMIO(0x9888), 0x1983002E },
	{ _MMIO(0x9888), 0x1B83002D },
	{ _MMIO(0x9888), 0x1D83002C },
	{ _MMIO(0x9888), 0x1F83002B },
	{ _MMIO(0x9888), 0x2183002A },
	{ _MMIO(0x9888), 0x05830000 },
	{ _MMIO(0x9888), 0x01840555 },
	{ _MMIO(0x9888), 0x23800071 },
	{ _MMIO(0x9888), 0x25800072 },
	{ _MMIO(0x9888), 0x05800000 },
	{ _MMIO(0x9888), 0x01805000 },
	{ _MMIO(0x9888), 0x03800555 },
	{ _MMIO(0x9888), 0x01865000 },
	{ _MMIO(0x9888), 0x03860555 },
	{ _MMIO(0x9888), 0x01875000 },
	{ _MMIO(0x9888), 0x03870555 },
	{ _MMIO(0x9888), 0x418000AA },
	{ _MMIO(0x9888), 0x4380000A },
	{ _MMIO(0x9888), 0x45800000 },
	{ _MMIO(0x9888), 0x47800000 },
	{ _MMIO(0x9888), 0x498000C8 },
	{ _MMIO(0x9888), 0x4B8000C8 },
	{ _MMIO(0x9888), 0x4D8000C8 },
	{ _MMIO(0x9888), 0x4F80014A },
	{ _MMIO(0x9888), 0x5180014A },
	{ _MMIO(0x9888), 0x5380014A },
	{ _MMIO(0x9888), 0x5580014A },
	{ _MMIO(0x9888), 0x578001CE },
	{ _MMIO(0x9888), 0x59800000 },
};

static int select_render_basic_config(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs =
		mux_config_render_basic;
	dev_priv->perf.oa.mux_regs_len =
		ARRAY_SIZE(mux_config_render_basic);

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_render_basic;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_render_basic);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_render_basic;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_render_basic);

	return 0;
}

int i915_oa_select_metric_set_chv(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs = NULL;
	dev_priv->perf.oa.mux_regs_len = 0;
	dev_priv->perf.oa.b_counter_regs = NULL;
	dev_priv->perf.oa.b_counter_regs_len = 0;
	dev_priv->perf.oa.flex_regs = NULL;
	dev_priv->perf.oa.flex_regs_len = 0;

	switch (dev_priv->perf.oa.metrics_set) {
	case METRIC_SET_ID_RENDER_BASIC:
		return select_render_basic_config(dev_priv);
	default:
		return -ENODEV;
	}
}

static ssize_t
show_render_basic_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_RENDER_BASIC);
}

static struct device_attribute dev_attr_render_basic_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_render_basic_id,
	.store = NULL,
};

static struct attribute *attrs_render_basic[] = {
	&dev_attr_render_basic_id.attr,
	NULL,
};

static struct attribute_group group_render_basic = {
	.name = "9d8a3af5-c02c-4a4a-b947-f1672469e0fb",
	.attrs =  attrs_render_basic,
};

int
i915_perf_init_sysfs_chv(struct drm_i915_private *dev_priv)
{
	int ret;

	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_render_basic);
	if (ret)
		goto error_render_basic;

	return 0;

error_render_basic:
	return ret;
}

void
i915_perf_deinit_sysfs_chv(struct drm_i915_private *dev_priv)
{
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_render_basic);
}
