/*
 * Autogenerated file, DO NOT EDIT manually!
 *
 * Copyright (c) 2015 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

#include <linux/sysfs.h>

#include "i915_drv.h"

enum metric_set_id {
	METRIC_SET_ID_RENDER_BASIC = 1,
};

int i915_oa_n_builtin_metric_sets_bdw = 1;

static const struct i915_oa_reg b_counter_config_render_basic[] = {
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x00800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x00800000 },
};

static const struct i915_oa_reg flex_eu_config_render_basic[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_render_basic_1_0_slices_0x01[] = {
	{ _MMIO(0x9888), 0x143F000F },
	{ _MMIO(0x9888), 0x14110014 },
	{ _MMIO(0x9888), 0x14310014 },
	{ _MMIO(0x9888), 0x14BF000F },
	{ _MMIO(0x9888), 0x13837BE0 },
	{ _MMIO(0x9888), 0x3B800060 },
	{ _MMIO(0x9888), 0x3D800005 },
	{ _MMIO(0x9888), 0x005C4000 },
	{ _MMIO(0x9888), 0x065C8000 },
	{ _MMIO(0x9888), 0x085CC000 },
	{ _MMIO(0x9888), 0x003D8000 },
	{ _MMIO(0x9888), 0x183D0800 },
	{ _MMIO(0x9888), 0x0A3F0023 },
	{ _MMIO(0x9888), 0x103F0000 },
	{ _MMIO(0x9888), 0x00584000 },
	{ _MMIO(0x9888), 0x08584000 },
	{ _MMIO(0x9888), 0x0A5A4000 },
	{ _MMIO(0x9888), 0x005B4000 },
	{ _MMIO(0x9888), 0x0E5B8000 },
	{ _MMIO(0x9888), 0x185B2400 },
	{ _MMIO(0x9888), 0x0A1D4000 },
	{ _MMIO(0x9888), 0x0C1F0800 },
	{ _MMIO(0x9888), 0x0E1FAA00 },
	{ _MMIO(0x9888), 0x00384000 },
	{ _MMIO(0x9888), 0x0E384000 },
	{ _MMIO(0x9888), 0x16384000 },
	{ _MMIO(0x9888), 0x18380001 },
	{ _MMIO(0x9888), 0x00392000 },
	{ _MMIO(0x9888), 0x06398000 },
	{ _MMIO(0x9888), 0x0839A000 },
	{ _MMIO(0x9888), 0x0A391000 },
	{ _MMIO(0x9888), 0x00104000 },
	{ _MMIO(0x9888), 0x08104000 },
	{ _MMIO(0x9888), 0x00110030 },
	{ _MMIO(0x9888), 0x08110031 },
	{ _MMIO(0x9888), 0x10110000 },
	{ _MMIO(0x9888), 0x00134000 },
	{ _MMIO(0x9888), 0x16130020 },
	{ _MMIO(0x9888), 0x06308000 },
	{ _MMIO(0x9888), 0x08308000 },
	{ _MMIO(0x9888), 0x06311800 },
	{ _MMIO(0x9888), 0x08311880 },
	{ _MMIO(0x9888), 0x10310000 },
	{ _MMIO(0x9888), 0x0E334000 },
	{ _MMIO(0x9888), 0x16330080 },
	{ _MMIO(0x9888), 0x0ABF1180 },
	{ _MMIO(0x9888), 0x10BF0000 },
	{ _MMIO(0x9888), 0x0ADA8000 },
	{ _MMIO(0x9888), 0x0A9D8000 },
	{ _MMIO(0x9888), 0x109F0002 },
	{ _MMIO(0x9888), 0x0AB94000 },
	{ _MMIO(0x9888), 0x0D888000 },
	{ _MMIO(0x9888), 0x018A8000 },
	{ _MMIO(0x9888), 0x0F8A8000 },
	{ _MMIO(0x9888), 0x198A8000 },
	{ _MMIO(0x9888), 0x1B8A00A0 },
	{ _MMIO(0x9888), 0x238B0020 },
	{ _MMIO(0x9888), 0x258B2550 },
	{ _MMIO(0x9888), 0x198C1000 },
	{ _MMIO(0x9888), 0x0B8D8000 },
	{ _MMIO(0x9888), 0x1F85AA80 },
	{ _MMIO(0x9888), 0x2185AAA0 },
	{ _MMIO(0x9888), 0x2385002A },
	{ _MMIO(0x9888), 0x0D831021 },
	{ _MMIO(0x9888), 0x0F83572F },
	{ _MMIO(0x9888), 0x01835680 },
	{ _MMIO(0x9888), 0x038315AC },
	{ _MMIO(0x9888), 0x0583002A },
	{ _MMIO(0x9888), 0x11830000 },
	{ _MMIO(0x9888), 0x19835400 },
	{ _MMIO(0x9888), 0x1B830001 },
	{ _MMIO(0x9888), 0x07830000 },
	{ _MMIO(0x9888), 0x09830000 },
	{ _MMIO(0x9888), 0x0184C000 },
	{ _MMIO(0x9888), 0x07848000 },
	{ _MMIO(0x9888), 0x0984C000 },
	{ _MMIO(0x9888), 0x0B84C000 },
	{ _MMIO(0x9888), 0x0D84C000 },
	{ _MMIO(0x9888), 0x0F84C000 },
	{ _MMIO(0x9888), 0x0384C000 },
	{ _MMIO(0x9888), 0x05844000 },
	{ _MMIO(0x9888), 0x1B80C137 },
	{ _MMIO(0x9888), 0x1D80C147 },
	{ _MMIO(0x9888), 0x21800000 },
	{ _MMIO(0x9888), 0x1180C000 },
	{ _MMIO(0x9888), 0x17808000 },
	{ _MMIO(0x9888), 0x1980C000 },
	{ _MMIO(0x9888), 0x1F80C000 },
	{ _MMIO(0x9888), 0x1380C000 },
	{ _MMIO(0x9888), 0x15804000 },
	{ _MMIO(0x0D24), 0x00000000 },
	{ _MMIO(0x9888), 0x4D801110 },
	{ _MMIO(0x9888), 0x4F800331 },
	{ _MMIO(0x9888), 0x43800802 },
	{ _MMIO(0x9888), 0x51800000 },
	{ _MMIO(0x9888), 0x45801465 },
	{ _MMIO(0x9888), 0x53801111 },
	{ _MMIO(0x9888), 0x478014A5 },
	{ _MMIO(0x9888), 0x31800000 },
	{ _MMIO(0x9888), 0x3F8014A5 },
	{ _MMIO(0x9888), 0x41800005 },
};

static const struct i915_oa_reg mux_config_render_basic_1_1_slices_0x02[] = {
	{ _MMIO(0x9888), 0x143F000F },
	{ _MMIO(0x9888), 0x14BF000F },
	{ _MMIO(0x9888), 0x14910014 },
	{ _MMIO(0x9888), 0x14B10014 },
	{ _MMIO(0x9888), 0x13837BE0 },
	{ _MMIO(0x9888), 0x3B800060 },
	{ _MMIO(0x9888), 0x3D800005 },
	{ _MMIO(0x9888), 0x0A3F0023 },
	{ _MMIO(0x9888), 0x103F0000 },
	{ _MMIO(0x9888), 0x0A5A4000 },
	{ _MMIO(0x9888), 0x0A1D4000 },
	{ _MMIO(0x9888), 0x0E1F8000 },
	{ _MMIO(0x9888), 0x0A391000 },
	{ _MMIO(0x9888), 0x00DC4000 },
	{ _MMIO(0x9888), 0x06DC8000 },
	{ _MMIO(0x9888), 0x08DCC000 },
	{ _MMIO(0x9888), 0x00BD8000 },
	{ _MMIO(0x9888), 0x18BD0800 },
	{ _MMIO(0x9888), 0x0ABF1180 },
	{ _MMIO(0x9888), 0x10BF0000 },
	{ _MMIO(0x9888), 0x00D84000 },
	{ _MMIO(0x9888), 0x08D84000 },
	{ _MMIO(0x9888), 0x0ADA8000 },
	{ _MMIO(0x9888), 0x00DB4000 },
	{ _MMIO(0x9888), 0x0EDB8000 },
	{ _MMIO(0x9888), 0x18DB2400 },
	{ _MMIO(0x9888), 0x0A9D8000 },
	{ _MMIO(0x9888), 0x0C9F0800 },
	{ _MMIO(0x9888), 0x0E9F2A00 },
	{ _MMIO(0x9888), 0x109F0002 },
	{ _MMIO(0x9888), 0x00B84000 },
	{ _MMIO(0x9888), 0x0EB84000 },
	{ _MMIO(0x9888), 0x16B84000 },
	{ _MMIO(0x9888), 0x18B80001 },
	{ _MMIO(0x9888), 0x00B92000 },
	{ _MMIO(0x9888), 0x06B98000 },
	{ _MMIO(0x9888), 0x08B9A000 },
	{ _MMIO(0x9888), 0x0AB94000 },
	{ _MMIO(0x9888), 0x00904000 },
	{ _MMIO(0x9888), 0x08904000 },
	{ _MMIO(0x9888), 0x00910030 },
	{ _MMIO(0x9888), 0x08910031 },
	{ _MMIO(0x9888), 0x10910000 },
	{ _MMIO(0x9888), 0x00934000 },
	{ _MMIO(0x9888), 0x16930020 },
	{ _MMIO(0x9888), 0x06B08000 },
	{ _MMIO(0x9888), 0x08B08000 },
	{ _MMIO(0x9888), 0x06B11800 },
	{ _MMIO(0x9888), 0x08B11880 },
	{ _MMIO(0x9888), 0x10B10000 },
	{ _MMIO(0x9888), 0x0EB34000 },
	{ _MMIO(0x9888), 0x16B30080 },
	{ _MMIO(0x9888), 0x01888000 },
	{ _MMIO(0x9888), 0x0D88B800 },
	{ _MMIO(0x9888), 0x1B8A0080 },
	{ _MMIO(0x9888), 0x238B0040 },
	{ _MMIO(0x9888), 0x258B26A0 },
	{ _MMIO(0x9888), 0x018C4000 },
	{ _MMIO(0x9888), 0x0F8C4000 },
	{ _MMIO(0x9888), 0x178C2000 },
	{ _MMIO(0x9888), 0x198C1100 },
	{ _MMIO(0x9888), 0x018D2000 },
	{ _MMIO(0x9888), 0x078D8000 },
	{ _MMIO(0x9888), 0x098DA000 },
	{ _MMIO(0x9888), 0x0B8D8000 },
	{ _MMIO(0x9888), 0x1F85AA80 },
	{ _MMIO(0x9888), 0x2185AAA0 },
	{ _MMIO(0x9888), 0x2385002A },
	{ _MMIO(0x9888), 0x0D831021 },
	{ _MMIO(0x9888), 0x0F83572F },
	{ _MMIO(0x9888), 0x01835680 },
	{ _MMIO(0x9888), 0x038315AC },
	{ _MMIO(0x9888), 0x0583002A },
	{ _MMIO(0x9888), 0x11830000 },
	{ _MMIO(0x9888), 0x19835400 },
	{ _MMIO(0x9888), 0x1B830001 },
	{ _MMIO(0x9888), 0x07830000 },
	{ _MMIO(0x9888), 0x09830000 },
	{ _MMIO(0x9888), 0x0184C000 },
	{ _MMIO(0x9888), 0x07848000 },
	{ _MMIO(0x9888), 0x0984C000 },
	{ _MMIO(0x9888), 0x0B84C000 },
	{ _MMIO(0x9888), 0x0D84C000 },
	{ _MMIO(0x9888), 0x0F84C000 },
	{ _MMIO(0x9888), 0x0384C000 },
	{ _MMIO(0x9888), 0x05844000 },
	{ _MMIO(0x9888), 0x1B80C137 },
	{ _MMIO(0x9888), 0x1D80C147 },
	{ _MMIO(0x9888), 0x21800000 },
	{ _MMIO(0x9888), 0x1180C000 },
	{ _MMIO(0x9888), 0x17808000 },
	{ _MMIO(0x9888), 0x1980C000 },
	{ _MMIO(0x9888), 0x1F80C000 },
	{ _MMIO(0x9888), 0x1380C000 },
	{ _MMIO(0x9888), 0x15804000 },
	{ _MMIO(0x0D24), 0x00000000 },
	{ _MMIO(0x9888), 0x4D805550 },
	{ _MMIO(0x9888), 0x4F800335 },
	{ _MMIO(0x9888), 0x43800802 },
	{ _MMIO(0x9888), 0x51800400 },
	{ _MMIO(0x9888), 0x458004A1 },
	{ _MMIO(0x9888), 0x53805555 },
	{ _MMIO(0x9888), 0x47800421 },
	{ _MMIO(0x9888), 0x31800000 },
	{ _MMIO(0x9888), 0x3F800421 },
	{ _MMIO(0x9888), 0x41800841 },
};

static int select_render_basic_config(struct drm_i915_private *dev_priv)
{
	if (INTEL_INFO(dev_priv)->slice_mask & 0x01) {
		dev_priv->perf.oa.mux_regs =
			mux_config_render_basic_1_0_slices_0x01;
		dev_priv->perf.oa.mux_regs_len =
			ARRAY_SIZE(mux_config_render_basic_1_0_slices_0x01);
	} else if (INTEL_INFO(dev_priv)->slice_mask & 0x02) {
		dev_priv->perf.oa.mux_regs =
			mux_config_render_basic_1_1_slices_0x02;
		dev_priv->perf.oa.mux_regs_len =
			ARRAY_SIZE(mux_config_render_basic_1_1_slices_0x02);
	} else {
		DRM_DEBUG_DRIVER("No suitable MUX config for \"RENDER_BASIC\" metric set");
		return -EINVAL;
	}

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_render_basic;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_render_basic);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_render_basic;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_render_basic);

	return 0;
}

int i915_oa_select_metric_set_bdw(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs = NULL;
	dev_priv->perf.oa.mux_regs_len = 0;
	dev_priv->perf.oa.b_counter_regs = NULL;
	dev_priv->perf.oa.b_counter_regs_len = 0;
	dev_priv->perf.oa.flex_regs = NULL;
	dev_priv->perf.oa.flex_regs_len = 0;

	switch (dev_priv->perf.oa.metrics_set) {
	case METRIC_SET_ID_RENDER_BASIC:
		return select_render_basic_config(dev_priv);
	default:
		return -ENODEV;
	}
}

static ssize_t
show_render_basic_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_RENDER_BASIC);
}

static struct device_attribute dev_attr_render_basic_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_render_basic_id,
	.store = NULL,
};

static struct attribute *attrs_render_basic[] = {
	&dev_attr_render_basic_id.attr,
	NULL,
};

static struct attribute_group group_render_basic = {
	.name = "b541bd57-0e0f-4154-b4c0-5858010a2bf7",
	.attrs =  attrs_render_basic,
};

int
i915_perf_init_sysfs_bdw(struct drm_i915_private *dev_priv)
{
	int ret;

	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_render_basic);
	if (ret)
		goto error_render_basic;

	return 0;

error_render_basic:
	return ret;
}

void
i915_perf_deinit_sysfs_bdw(struct drm_i915_private *dev_priv)
{
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_render_basic);
}
