/*
 * Autogenerated file, DO NOT EDIT manually!
 *
 * Copyright (c) 2015 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

#include "i915_drv.h"

const struct i915_oa_reg i915_oa_3d_b_counter_config_chv[] = {
	{ 0x2710, 0x00000000 },
	{ 0x2714, 0x00800000 },
	{ 0x2720, 0x00000000 },
	{ 0x2724, 0x00800000 },
};
const int i915_oa_3d_b_counter_config_chv_len = 4;

const struct i915_oa_reg i915_oa_3d_flex_eu_config_chv[] = {
	{ 0xE458, 0x00005004 },
	{ 0xE558, 0x00010003 },
	{ 0xE658, 0x00012011 },
	{ 0xE758, 0x00015014 },
	{ 0xE45c, 0x00051050 },
	{ 0xE55c, 0x00053052 },
	{ 0xE65c, 0x00055054 },
};
const int i915_oa_3d_flex_eu_config_chv_len = 7;

const struct i915_oa_reg i915_oa_3d_mux_config_chv[] = {
	{ 0x9888, 0x59800000 },
	{ 0x9888, 0x59800001 },
	{ 0x9888, 0x2C110014 },
	{ 0x9888, 0x2E110000 },
	{ 0x9888, 0x2C310014 },
	{ 0x9888, 0x2E310000 },
	{ 0x9888, 0x2B8303DF },
	{ 0x9888, 0x358002C0 },
	{ 0x9888, 0x00580888 },
	{ 0x9888, 0x00190555 },
	{ 0x9888, 0x00380444 },
	{ 0x9888, 0x003A0666 },
	{ 0x9888, 0x00100111 },
	{ 0x9888, 0x06110030 },
	{ 0x9888, 0x0A110031 },
	{ 0x9888, 0x0E110046 },
	{ 0x9888, 0x04110000 },
	{ 0x9888, 0x00110000 },
	{ 0x9888, 0x00130111 },
	{ 0x9888, 0x00300444 },
	{ 0x9888, 0x08310030 },
	{ 0x9888, 0x0C310031 },
	{ 0x9888, 0x10310046 },
	{ 0x9888, 0x04310000 },
	{ 0x9888, 0x00310000 },
	{ 0x9888, 0x00330444 },
	{ 0x9888, 0x018B0FFF },
	{ 0x9888, 0x01855000 },
	{ 0x9888, 0x03850555 },
	{ 0x9888, 0x13830021 },
	{ 0x9888, 0x15830020 },
	{ 0x9888, 0x1783002F },
	{ 0x9888, 0x1983002E },
	{ 0x9888, 0x1B83002D },
	{ 0x9888, 0x1D83002C },
	{ 0x9888, 0x1F83002B },
	{ 0x9888, 0x2183002A },
	{ 0x9888, 0x05830000 },
	{ 0x9888, 0x01840555 },
	{ 0x9888, 0x23800071 },
	{ 0x9888, 0x25800072 },
	{ 0x9888, 0x05800000 },
	{ 0x9888, 0x01805000 },
	{ 0x9888, 0x03800555 },
	{ 0x9888, 0x01865000 },
	{ 0x9888, 0x03860555 },
	{ 0x9888, 0x01875000 },
	{ 0x9888, 0x03870555 },
	{ 0x9888, 0x418000AA },
	{ 0x9888, 0x4380000A },
	{ 0x9888, 0x45800000 },
	{ 0x9888, 0x47800000 },
	{ 0x9888, 0x498000C8 },
	{ 0x9888, 0x4B8000C8 },
	{ 0x9888, 0x4D8000C8 },
	{ 0x9888, 0x4F80014A },
	{ 0x9888, 0x5180014A },
	{ 0x9888, 0x5380014A },
	{ 0x9888, 0x5580014A },
	{ 0x9888, 0x578001CE },
	{ 0x9888, 0x59800000 },
};
const int i915_oa_3d_mux_config_chv_len = 61;
