/*
 * Autogenerated file, DO NOT EDIT manually!
 *
 * Copyright (c) 2015 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

#include <linux/sysfs.h>

#include "i915_drv.h"

enum metric_set_id {
	METRIC_SET_ID_RENDER_BASIC = 1,
};

int i915_oa_n_builtin_metric_sets_skl = 1;

static const struct i915_oa_reg b_counter_config_render_basic[] = {
	{ _MMIO(0x2710), 0x00000000 },
	{ _MMIO(0x2714), 0x00800000 },
	{ _MMIO(0x2720), 0x00000000 },
	{ _MMIO(0x2724), 0x00800000 },
};

static const struct i915_oa_reg flex_eu_config_render_basic[] = {
	{ _MMIO(0xE458), 0x00005004 },
	{ _MMIO(0xE558), 0x00010003 },
	{ _MMIO(0xE658), 0x00012011 },
	{ _MMIO(0xE758), 0x00015014 },
	{ _MMIO(0xE45c), 0x00051050 },
	{ _MMIO(0xE55c), 0x00053052 },
	{ _MMIO(0xE65c), 0x00055054 },
};

static const struct i915_oa_reg mux_config_render_basic_1_1_sku_lt_0x02[] = {
	{ _MMIO(0x9888), 0x166C01E0 },
	{ _MMIO(0x9888), 0x12170280 },
	{ _MMIO(0x9888), 0x12370280 },
	{ _MMIO(0x9888), 0x159303DF },
	{ _MMIO(0x9888), 0x3F901403 },
	{ _MMIO(0x9888), 0x1A4E0080 },
	{ _MMIO(0x9888), 0x0A6C0053 },
	{ _MMIO(0x9888), 0x106C0000 },
	{ _MMIO(0x9888), 0x1C6C0000 },
	{ _MMIO(0x9888), 0x0A1B4000 },
	{ _MMIO(0x9888), 0x1C1C0001 },
	{ _MMIO(0x9888), 0x002F1000 },
	{ _MMIO(0x9888), 0x042F1000 },
	{ _MMIO(0x9888), 0x004C4000 },
	{ _MMIO(0x9888), 0x0A4C8400 },
	{ _MMIO(0x9888), 0x000D2000 },
	{ _MMIO(0x9888), 0x060D8000 },
	{ _MMIO(0x9888), 0x080DA000 },
	{ _MMIO(0x9888), 0x0A0D2000 },
	{ _MMIO(0x9888), 0x0C0F0400 },
	{ _MMIO(0x9888), 0x0E0F6600 },
	{ _MMIO(0x9888), 0x002C8000 },
	{ _MMIO(0x9888), 0x162C2200 },
	{ _MMIO(0x9888), 0x062D8000 },
	{ _MMIO(0x9888), 0x082D8000 },
	{ _MMIO(0x9888), 0x00133000 },
	{ _MMIO(0x9888), 0x08133000 },
	{ _MMIO(0x9888), 0x00170020 },
	{ _MMIO(0x9888), 0x08170021 },
	{ _MMIO(0x9888), 0x10170000 },
	{ _MMIO(0x9888), 0x0633C000 },
	{ _MMIO(0x9888), 0x0833C000 },
	{ _MMIO(0x9888), 0x06370800 },
	{ _MMIO(0x9888), 0x08370840 },
	{ _MMIO(0x9888), 0x10370000 },
	{ _MMIO(0x9888), 0x0D933031 },
	{ _MMIO(0x9888), 0x0F933E3F },
	{ _MMIO(0x9888), 0x01933D00 },
	{ _MMIO(0x9888), 0x03933B3C },
	{ _MMIO(0x9888), 0x0593003A },
	{ _MMIO(0x9888), 0x1D930000 },
	{ _MMIO(0x9888), 0x1B930000 },
	{ _MMIO(0x9888), 0x13930000 },
	{ _MMIO(0x9888), 0x17930000 },
	{ _MMIO(0x9888), 0x1F952A80 },
	{ _MMIO(0x9888), 0x1D9500AA },
	{ _MMIO(0x9888), 0x1D900157 },
	{ _MMIO(0x9888), 0x1F900167 },
	{ _MMIO(0x9888), 0x35900000 },
	{ _MMIO(0x9888), 0x2B908000 },
	{ _MMIO(0x9888), 0x2D908000 },
	{ _MMIO(0x9888), 0x2F908000 },
	{ _MMIO(0x9888), 0x31908000 },
	{ _MMIO(0x9888), 0x15908000 },
	{ _MMIO(0x9888), 0x17908000 },
	{ _MMIO(0x9888), 0x19908000 },
	{ _MMIO(0x9888), 0x1B908000 },
	{ _MMIO(0x0D28), 0x00000000 },
	{ _MMIO(0x9888), 0x1190001F },
	{ _MMIO(0x9888), 0x51901100 },
	{ _MMIO(0x9888), 0x41900020 },
	{ _MMIO(0x9888), 0x55900000 },
	{ _MMIO(0x9888), 0x45900C42 },
	{ _MMIO(0x9888), 0x47900061 },
	{ _MMIO(0x9888), 0x57901110 },
	{ _MMIO(0x9888), 0x49900000 },
	{ _MMIO(0x9888), 0x37900000 },
	{ _MMIO(0x9888), 0x33900000 },
	{ _MMIO(0x9888), 0x4B900000 },
	{ _MMIO(0x9888), 0x59900001 },
	{ _MMIO(0x9888), 0x43900000 },
	{ _MMIO(0x9888), 0x53901111 },
};

static const struct i915_oa_reg mux_config_render_basic_1_1_sku_gte_0x02[] = {
	{ _MMIO(0x00009888), 0x166C01E0 },
	{ _MMIO(0x00009888), 0x12170280 },
	{ _MMIO(0x00009888), 0x12370280 },
	{ _MMIO(0x00009888), 0x159303DF },
	{ _MMIO(0x00009888), 0x3F901403 },
	{ _MMIO(0x00009888), 0x1A4E0080 },
	{ _MMIO(0x00009888), 0x0A6C0053 },
	{ _MMIO(0x00009888), 0x106C0000 },
	{ _MMIO(0x00009888), 0x1C6C0000 },
	{ _MMIO(0x00009888), 0x0A1B4000 },
	{ _MMIO(0x00009888), 0x1C1C0001 },
	{ _MMIO(0x00009888), 0x002F1000 },
	{ _MMIO(0x00009888), 0x042F1000 },
	{ _MMIO(0x00009888), 0x004C4000 },
	{ _MMIO(0x00009888), 0x0A4C8400 },
	{ _MMIO(0x00009888), 0x000D2000 },
	{ _MMIO(0x00009888), 0x060D8000 },
	{ _MMIO(0x00009888), 0x080DA000 },
	{ _MMIO(0x00009888), 0x0A0D2000 },
	{ _MMIO(0x00009888), 0x0C0F0400 },
	{ _MMIO(0x00009888), 0x0E0F6600 },
	{ _MMIO(0x00009888), 0x002C8000 },
	{ _MMIO(0x00009888), 0x162C2200 },
	{ _MMIO(0x00009888), 0x062D8000 },
	{ _MMIO(0x00009888), 0x082D8000 },
	{ _MMIO(0x00009888), 0x00133000 },
	{ _MMIO(0x00009888), 0x08133000 },
	{ _MMIO(0x00009888), 0x00170020 },
	{ _MMIO(0x00009888), 0x08170021 },
	{ _MMIO(0x00009888), 0x10170000 },
	{ _MMIO(0x00009888), 0x0633C000 },
	{ _MMIO(0x00009888), 0x0833C000 },
	{ _MMIO(0x00009888), 0x06370800 },
	{ _MMIO(0x00009888), 0x08370840 },
	{ _MMIO(0x00009888), 0x10370000 },
	{ _MMIO(0x00009888), 0x0D933031 },
	{ _MMIO(0x00009888), 0x0F933E3F },
	{ _MMIO(0x00009888), 0x01933D00 },
	{ _MMIO(0x00009888), 0x03933B3C },
	{ _MMIO(0x00009888), 0x0593003A },
	{ _MMIO(0x00009888), 0x11930000 },
	{ _MMIO(0x00009888), 0x1D930000 },
	{ _MMIO(0x00009888), 0x19930000 },
	{ _MMIO(0x00009888), 0x1B930000 },
	{ _MMIO(0x00009888), 0x1D900157 },
	{ _MMIO(0x00009888), 0x1F900167 },
	{ _MMIO(0x00009888), 0x35900000 },
	{ _MMIO(0x00009888), 0x2B908000 },
	{ _MMIO(0x00009888), 0x2D908000 },
	{ _MMIO(0x00009888), 0x2F908000 },
	{ _MMIO(0x00009888), 0x31908000 },
	{ _MMIO(0x00009888), 0x15908000 },
	{ _MMIO(0x00009888), 0x17908000 },
	{ _MMIO(0x00009888), 0x19908000 },
	{ _MMIO(0x00009888), 0x1B908000 },
	{ _MMIO(0x00009888), 0x1190001F },
	{ _MMIO(0x00009888), 0x51901100 },
	{ _MMIO(0x00009888), 0x41900420 },
	{ _MMIO(0x00009888), 0x55900000 },
	{ _MMIO(0x00009888), 0x45900C42 },
	{ _MMIO(0x00009888), 0x47900061 },
	{ _MMIO(0x00009888), 0x57901110 },
	{ _MMIO(0x00009888), 0x49900420 },
	{ _MMIO(0x00009888), 0x37900000 },
	{ _MMIO(0x00009888), 0x33900000 },
	{ _MMIO(0x00009888), 0x4B900021 },
	{ _MMIO(0x00009888), 0x59900001 },
	{ _MMIO(0x00009888), 0x43900421 },
	{ _MMIO(0x00009888), 0x53901111 },
};

static int select_render_basic_config(struct drm_i915_private *dev_priv)
{
	if (dev_priv->dev->pdev->revision < 0x02) {
		dev_priv->perf.oa.mux_regs =
			mux_config_render_basic_1_1_sku_lt_0x02;
		dev_priv->perf.oa.mux_regs_len =
			ARRAY_SIZE(mux_config_render_basic_1_1_sku_lt_0x02);
	} else if (dev_priv->dev->pdev->revision >= 0x02) {
		dev_priv->perf.oa.mux_regs =
			mux_config_render_basic_1_1_sku_gte_0x02;
		dev_priv->perf.oa.mux_regs_len =
			ARRAY_SIZE(mux_config_render_basic_1_1_sku_gte_0x02);
	} else {
		DRM_DEBUG_DRIVER("No suitable MUX config for \"RENDER_BASIC\" metric set");
		return -EINVAL;
	}

	dev_priv->perf.oa.b_counter_regs =
		b_counter_config_render_basic;
	dev_priv->perf.oa.b_counter_regs_len =
		ARRAY_SIZE(b_counter_config_render_basic);

	dev_priv->perf.oa.flex_regs =
		flex_eu_config_render_basic;
	dev_priv->perf.oa.flex_regs_len =
		ARRAY_SIZE(flex_eu_config_render_basic);

	return 0;
}

int i915_oa_select_metric_set_skl(struct drm_i915_private *dev_priv)
{
	dev_priv->perf.oa.mux_regs = NULL;
	dev_priv->perf.oa.mux_regs_len = 0;
	dev_priv->perf.oa.b_counter_regs = NULL;
	dev_priv->perf.oa.b_counter_regs_len = 0;
	dev_priv->perf.oa.flex_regs = NULL;
	dev_priv->perf.oa.flex_regs_len = 0;

	switch (dev_priv->perf.oa.metrics_set) {
	case METRIC_SET_ID_RENDER_BASIC:
		return select_render_basic_config(dev_priv);
	default:
		return -ENODEV;
	}
}

static ssize_t
show_render_basic_id(struct device *kdev, struct device_attribute *attr, char *buf)
{
	return sprintf(buf, "%d\n", METRIC_SET_ID_RENDER_BASIC);
}

static struct device_attribute dev_attr_render_basic_id = {
	.attr = { .name = "id", .mode = S_IRUGO },
	.show = show_render_basic_id,
	.store = NULL,
};

static struct attribute *attrs_render_basic[] = {
	&dev_attr_render_basic_id.attr,
	NULL,
};

static struct attribute_group group_render_basic = {
	.name = "fdfc01cc-e28e-423a-aae0-b5ed5d4d7a9f",
	.attrs =  attrs_render_basic,
};

int
i915_perf_init_sysfs_skl(struct drm_i915_private *dev_priv)
{
	int ret;

	ret = sysfs_create_group(dev_priv->perf.metrics_kobj, &group_render_basic);
	if (ret)
		goto error_render_basic;

	return 0;

error_render_basic:
	return ret;
}

void
i915_perf_deinit_sysfs_skl(struct drm_i915_private *dev_priv)
{
	sysfs_remove_group(dev_priv->perf.metrics_kobj, &group_render_basic);
}
