/*
 * Autogenerated file, DO NOT EDIT manually!
 *
 * Copyright (c) 2015 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

#ifndef __I915_OA_SKL_H__
#define __I915_OA_SKL_H__

/* SKL Render Metrics Basic Gen9 */
extern const struct i915_oa_reg i915_oa_3d_b_counter_config_skl[];
extern const int i915_oa_3d_b_counter_config_skl_len;
extern const struct i915_oa_reg i915_oa_3d_flex_eu_config_skl[];
extern const int i915_oa_3d_flex_eu_config_skl_len;
extern const struct i915_oa_reg i915_oa_3d_mux_config_1_1_sku_0x02_ult_skl[];
extern const int i915_oa_3d_mux_config_1_1_sku_0x02_ult_skl_len;
extern const struct i915_oa_reg i915_oa_3d_mux_config_1_1_sku_0x02_ugte_skl[];
extern const int i915_oa_3d_mux_config_1_1_sku_0x02_ugte_skl_len;

#endif
