/*
 * Autogenerated file, DO NOT EDIT manually!
 *
 * Copyright (c) 2015 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 */

#ifndef __I915_OA_BDW_H__
#define __I915_OA_BDW_H__

/* BDW Render Metrics Basic Gen8 */
extern const struct i915_oa_reg i915_oa_3d_b_counter_config_bdw[];
extern const int i915_oa_3d_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_3d_flex_eu_config_bdw[];
extern const int i915_oa_3d_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_3d_mux_config_1_0_slice_mask_0x01_bdw[];
extern const int i915_oa_3d_mux_config_1_0_slice_mask_0x01_bdw_len;
extern const struct i915_oa_reg i915_oa_3d_mux_config_1_1_slice_mask_0x02_bdw[];
extern const int i915_oa_3d_mux_config_1_1_slice_mask_0x02_bdw_len;

/* BDW Compute Metrics Basic Gen8 */
extern const struct i915_oa_reg i915_oa_compute_b_counter_config_bdw[];
extern const int i915_oa_compute_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_flex_eu_config_bdw[];
extern const int i915_oa_compute_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_mux_config_1_0_slice_mask_0x01_bdw[];
extern const int i915_oa_compute_mux_config_1_0_slice_mask_0x01_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_mux_config_1_2_slice_mask_0x02_bdw[];
extern const int i915_oa_compute_mux_config_1_2_slice_mask_0x02_bdw_len;

/* BDW Render Metrics for 3D Pipeline Profile */
extern const struct i915_oa_reg i915_oa_render_pipe_profile_b_counter_config_bdw[];
extern const int i915_oa_render_pipe_profile_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_render_pipe_profile_flex_eu_config_bdw[];
extern const int i915_oa_render_pipe_profile_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_render_pipe_profile_mux_config_bdw[];
extern const int i915_oa_render_pipe_profile_mux_config_bdw_len;

/* BDW Memory Reads Distribution Gen8 */
extern const struct i915_oa_reg i915_oa_memory_reads_b_counter_config_bdw[];
extern const int i915_oa_memory_reads_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_memory_reads_flex_eu_config_bdw[];
extern const int i915_oa_memory_reads_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_memory_reads_mux_config_bdw[];
extern const int i915_oa_memory_reads_mux_config_bdw_len;

/* BDW Memory Writes Distribution Gen8 */
extern const struct i915_oa_reg i915_oa_memory_writes_b_counter_config_bdw[];
extern const int i915_oa_memory_writes_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_memory_writes_flex_eu_config_bdw[];
extern const int i915_oa_memory_writes_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_memory_writes_mux_config_bdw[];
extern const int i915_oa_memory_writes_mux_config_bdw_len;

/* BDW Compute Metrics Extended Gen8 */
extern const struct i915_oa_reg i915_oa_compute_extended_b_counter_config_bdw[];
extern const int i915_oa_compute_extended_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_extended_flex_eu_config_bdw[];
extern const int i915_oa_compute_extended_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_extended_mux_config_1_0_subslice_mask_0x01_bdw[];
extern const int i915_oa_compute_extended_mux_config_1_0_subslice_mask_0x01_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_extended_mux_config_1_1_subslice_mask_0x08_bdw[];
extern const int i915_oa_compute_extended_mux_config_1_1_subslice_mask_0x08_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_extended_mux_config_1_2_subslice_mask_0x02_bdw[];
extern const int i915_oa_compute_extended_mux_config_1_2_subslice_mask_0x02_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_extended_mux_config_1_3_subslice_mask_0x10_bdw[];
extern const int i915_oa_compute_extended_mux_config_1_3_subslice_mask_0x10_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_extended_mux_config_1_4_subslice_mask_0x04_bdw[];
extern const int i915_oa_compute_extended_mux_config_1_4_subslice_mask_0x04_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_extended_mux_config_1_5_subslice_mask_0x20_bdw[];
extern const int i915_oa_compute_extended_mux_config_1_5_subslice_mask_0x20_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_extended_mux_config_bdw[];
extern const int i915_oa_compute_extended_mux_config_bdw_len;

/* BDW Compute Metrics L3 Cache Gen8 */
extern const struct i915_oa_reg i915_oa_compute_l3_cache_b_counter_config_bdw[];
extern const int i915_oa_compute_l3_cache_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_l3_cache_flex_eu_config_bdw[];
extern const int i915_oa_compute_l3_cache_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_compute_l3_cache_mux_config_bdw[];
extern const int i915_oa_compute_l3_cache_mux_config_bdw_len;

/* BDW Data Port Reads Coalescing Gen8 */
extern const struct i915_oa_reg i915_oa_data_port_reads_coalescing_b_counter_config_bdw[];
extern const int i915_oa_data_port_reads_coalescing_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_data_port_reads_coalescing_flex_eu_config_bdw[];
extern const int i915_oa_data_port_reads_coalescing_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_data_port_reads_coalescing_mux_config_1_0_subslice_mask_0x01_bdw[];
extern const int i915_oa_data_port_reads_coalescing_mux_config_1_0_subslice_mask_0x01_bdw_len;

/* BDW Data Port Writes Coalescing Gen8 */
extern const struct i915_oa_reg i915_oa_data_port_writes_coalescing_b_counter_config_bdw[];
extern const int i915_oa_data_port_writes_coalescing_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_data_port_writes_coalescing_flex_eu_config_bdw[];
extern const int i915_oa_data_port_writes_coalescing_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_data_port_writes_coalescing_mux_config_1_0_subslice_mask_0x01_bdw[];
extern const int i915_oa_data_port_writes_coalescing_mux_config_1_0_subslice_mask_0x01_bdw_len;

/* BDW Metric set L3_1 */
extern const struct i915_oa_reg i915_oa_l3_1_b_counter_config_bdw[];
extern const int i915_oa_l3_1_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_l3_1_flex_eu_config_bdw[];
extern const int i915_oa_l3_1_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_l3_1_mux_config_bdw[];
extern const int i915_oa_l3_1_mux_config_bdw_len;

/* BDW Metric set L3_2 */
extern const struct i915_oa_reg i915_oa_l3_2_b_counter_config_bdw[];
extern const int i915_oa_l3_2_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_l3_2_flex_eu_config_bdw[];
extern const int i915_oa_l3_2_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_l3_2_mux_config_bdw[];
extern const int i915_oa_l3_2_mux_config_bdw_len;

/* BDW Metric set L3_3 */
extern const struct i915_oa_reg i915_oa_l3_3_b_counter_config_bdw[];
extern const int i915_oa_l3_3_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_l3_3_flex_eu_config_bdw[];
extern const int i915_oa_l3_3_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_l3_3_mux_config_bdw[];
extern const int i915_oa_l3_3_mux_config_bdw_len;

/* BDW Metric set L3_4 */
extern const struct i915_oa_reg i915_oa_l3_4_b_counter_config_bdw[];
extern const int i915_oa_l3_4_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_l3_4_flex_eu_config_bdw[];
extern const int i915_oa_l3_4_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_l3_4_mux_config_bdw[];
extern const int i915_oa_l3_4_mux_config_bdw_len;

/* BDW Metric set RasterizerAndPixelBackend */
extern const struct i915_oa_reg i915_oa_rasterizer_and_pixel_backend_b_counter_config_bdw[];
extern const int i915_oa_rasterizer_and_pixel_backend_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_rasterizer_and_pixel_backend_flex_eu_config_bdw[];
extern const int i915_oa_rasterizer_and_pixel_backend_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_rasterizer_and_pixel_backend_mux_config_bdw[];
extern const int i915_oa_rasterizer_and_pixel_backend_mux_config_bdw_len;

/* BDW Metric set Sampler_1 */
extern const struct i915_oa_reg i915_oa_sampler_1_b_counter_config_bdw[];
extern const int i915_oa_sampler_1_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_sampler_1_flex_eu_config_bdw[];
extern const int i915_oa_sampler_1_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_sampler_1_mux_config_bdw[];
extern const int i915_oa_sampler_1_mux_config_bdw_len;

/* BDW Metric set Sampler_2 */
extern const struct i915_oa_reg i915_oa_sampler_2_b_counter_config_bdw[];
extern const int i915_oa_sampler_2_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_sampler_2_flex_eu_config_bdw[];
extern const int i915_oa_sampler_2_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_sampler_2_mux_config_bdw[];
extern const int i915_oa_sampler_2_mux_config_bdw_len;

/* BDW Metric set TDL_1 */
extern const struct i915_oa_reg i915_oa_tdl_1_b_counter_config_bdw[];
extern const int i915_oa_tdl_1_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_tdl_1_flex_eu_config_bdw[];
extern const int i915_oa_tdl_1_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_tdl_1_mux_config_bdw[];
extern const int i915_oa_tdl_1_mux_config_bdw_len;

/* BDW Metric set TDL_2 */
extern const struct i915_oa_reg i915_oa_tdl_2_b_counter_config_bdw[];
extern const int i915_oa_tdl_2_b_counter_config_bdw_len;
extern const struct i915_oa_reg i915_oa_tdl_2_flex_eu_config_bdw[];
extern const int i915_oa_tdl_2_flex_eu_config_bdw_len;
extern const struct i915_oa_reg i915_oa_tdl_2_mux_config_bdw[];
extern const int i915_oa_tdl_2_mux_config_bdw_len;

#endif
